spring:
  datasource:
    url: jdbc:mysql://coin-mysql:3306/coin?allowPublicKeyRetrieval=true&useSSL=false
    username: coin_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

pickup-server:
  base-url: http://pickup-server:8080

logging:
  file:
    path: /logs
